[build-system]
requires = ["setuptools>=68.0", "wheel", "Cython>=3.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
version = "0.1.6"
name = "farms_core"
description = "FARMS core package"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">= 3.11"
dependencies = [
    "numpy",
    "PyYAML",
    "trimesh",
    "scipy",
    "h5py",
    "matplotlib",
    "cycler",
    "colorama",
]
keywords = ["farms", "framework", "animals", "robot", "modeling", "simulation"]
classifiers = [
  "Development Status :: 4 - Beta",
  # Indicate who your project is intended for
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Scientific/Engineering :: Artificial Life",
  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
]

[project.optional-dependencies]
cli = [
  "rich",
]

[project.urls]
Homepage = "https://farmsim.dev"
Documentation = "https://farmsim.dev"
Repository = "https://github.com/farmsim/farms_core.git"
Issues = "https://github.com/farmsim/farms_core/issues"
Changelog = "https://github.com/farmsim/farms_core/blob/main/CHANGELOG.md"

[tool.setuptools.packages.find]
# This is equivalent to find_packages() with no arguments

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-dir]
farms_core = "farms_core"

[tool.setuptools.package-data]
farms_core = [
    "*.pxd",
    "array/*.pxd",
    "sensors/*.pxd",
    "model/*.pxd",
    "utils/*.pxd"
]